### ISSUE TITLE
API Reference web pages are indistinguishable in browser tabs and bookmarks because the <title>s are all "Atom"

### ISSUE THREAD

**Issue by WalterGR** [atom/docs#159] opened 2016-01-14 08:09 UTC
The 4 tabs that say "Atom" are all showing different API Reference pages for different Atom versions:

<img width="250" alt="atom-api-pages-all-have-the-same-title" src="https://cloud.githubusercontent.com/assets/380880/12318880/ab2ac926-ba52-11e5-9a35-f2c8591d4d7d.png">

All the "API Reference" URLs I've checked have HTML that just says -

      <title>Atom</title>

**Comment by 50Wliu** [comment] 2016-01-14 12:30
Hi @WalterGR, this is a duplicate of atom/atom.io#17 - please subscribe there for updates!

**Closed by 50Wliu** 2016-01-14 12:30 UTC

**Comment by WalterGR** [comment] 2016-01-14 23:48
Sorry about that!  I looked over the open issues tagged with `atom.io` in this repo (`atom/docs`) and not in the `atom/atom.io` repo.

Thanks for the link.

**Comment by 50Wliu** [comment] 2016-01-14 23:52
No worries :smile:.  All this modularity can get confusing at times :P.
