### ISSUE TITLE
Getting Started Side Menu on Website is incorrect

### ISSUE THREAD

**Issue by TheAlphaNerd** [atom/docs#137] opened 2015-10-21 00:20 UTC
After clicking getting started the side panel only has links about upgrading to 1.0

This is very confusing as a new user

**Comment by 50Wliu** [comment] 2015-10-21 00:56
This looks like a duplicate of #121 - please subscribe there for updates (and also, the docs that you're looking for :smile:).

**Closed by 50Wliu** 2015-10-21 00:56 UTC

**Comment by izuzak** [comment] 2015-10-21 06:35
cc @thedaniel seems like more and more users are hitting this problem. Just a friendly ping in case that helps us prioritize tasks. :v:
