### ISSUE TITLE
https://atom.io/docs "Getting Started" link is wrong

### ISSUE THREAD

**Issue by nicdumz** [atom/docs#162] opened 2016-01-18 11:22 UTC
Hey folks,

Not sure where to leave feedback, hoping that starting here is good.

The current "Getting Started" link at https://atom.io/docs points to https://atom.io/docs/v1.4.0/upgrading-to-1-0-apis-upgrading-your-package , that's somewhat confusing. 

The menu on the left also seems to have ordering issues. To me, https://atom.io/docs/v1.4.0/getting-started-summary shows on the left side:

1 : Getting Started
1.1 Upgrading Your Package
1.2 Upgrading Your UI Theme Or Package Selectors
1.3 Upgrading Your Syntax Theme
1.4 Summary

Seems like the Upgrade things accidentally made it to the "Getting Started" section?

**Comment by 50Wliu** [comment] 2016-01-18 15:45
Hi @nicdumz, thanks for reporting!  This looks like a duplicate of #155 though, so please subscribe there for updates.

**Closed by 50Wliu** 2016-01-18 15:45 UTC
